version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: gomod
    directory: /gogit
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: github.com/git-pkgs/clone

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
